# Site settings
title: "Duc Do Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Duc Do"
resume_title:                   "Data Science & AI ethusiastic"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dod2@myumanitoba.ca"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "1-431-556-7336"
resume_contact_address:         "Winnipeg, Manitoba, Canada"

resume_header_contact_info:     "Winnipeg, Manitoba, Canada • 431-556-7336 • duc.do.nghiem@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a current undergraduate Co-op Data Science student at University of Manitoba. Before transitioning my academic career to Canada, I was an undergraduate science student majoring in Data Science and Artificial Intelligence at Hanoi University of Science and Technology, Vietnam.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ducdonghiem"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/duc-do-nghiem-27412824a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
